//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoadVehicleBreakdownAssistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int cust_id { get; set; }
        public string cust_full_name { get; set; }
        public string cust_email { get; set; }
        public Nullable<int> cust_age { get; set; }
        public string cust_mob_no { get; set; }
    }
}
