//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoadVehicleBreakdownAssistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int cust_srv_id { get; set; }
        public string cust_srv_name { get; set; }
        public string cust_srv_email { get; set; }
        public string cust_srv_mob_no { get; set; }
        public string cust_srv_type { get; set; }
        public Nullable<System.DateTime> cust_srv_date { get; set; }
        public string cust_srv_status { get; set; }
    }
}
